<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @author Emiliano Viada
 */
class AuctionRepository extends EntityRepository
{
	/**
	 * search() method
	 * @param array $fields
	 */
	public function search($fields)
	{
		$q = $this->getEntityManager()
			->createQueryBuilder()
			->select('a')
            ->from('AppBundle:Auction', 'a')
            ->where('1 = 1');

        // Filter by status?
        if (isset($fields['status']) && $fields['status'] != '') {
        	$q->andWhere('a.status = :status')
        		->setParameter('status', $fields['status']);
        }

        // Filter by locality?
        if (isset($fields['locality']) && $fields['locality'] != '') {
        	$q->andWhere('a.locality = :locality')
        		->setParameter('locality', $fields['locality']);
        }

        return $q->getQuery()->getResult();
	}
}
